version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql
    container_name: solid_principles_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - solid_principles

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: solid_principles_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - solid_principles

  # Symfony apache project container
  www:
    build: docker/php
    container_name: solid_principles_symfony
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - solid_principles

networks:
  solid_principles:

volumes:
  db-data:
